name: open_mail_app_plus
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  url_launcher: ^6.0.0
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:

  plugin:
    platforms:
      android:
        package: app.istoria.open_mail_app_plus
        pluginClass: OpenMailAppPlusPlugin
      ios:
        pluginClass: OpenMailAppPlusPlugin
